"""Generate apps/mobile/src/components/ui/icons.generated.ts from the brand-kit icons.

Usage:  python scripts/gen-icons.py
Reads every 24x24 line icon in apps/web/assets/icons and emits a TypeScript map of
{ name: [ {d, fill?}... ] } that the <Icon> component renders with react-native-svg.
"""
import json, pathlib, re

root = pathlib.Path(__file__).resolve().parent.parent
src = root / "apps/web/assets/icons"
out = root / "apps/mobile/src/components/ui/icons.generated.ts"
icons = {}
for f in sorted(src.glob("*.svg")):
    svg = f.read_text(encoding="utf-8")
    paths = []
    for m in re.finditer(r"<path\b([^>]*)/?>", svg):
        attrs = m.group(1)
        d = re.search(r'\bd="([^"]+)"', attrs)
        if not d:
            continue
        entry = {"d": d.group(1)}
        if re.search(r'fill="currentColor"', attrs):
            entry["fill"] = True
        paths.append(entry)
    for m in re.finditer(r"<(circle|rect|line|polyline|polygon)\b[^>]*>", svg):
        paths.append({"raw": m.group(0)})
    icons[f.stem] = paths
ts = "// AUTO-GENERATED by scripts/gen-icons.py from the Dermora brand kit. Do not edit.\n"
ts += "export type IconName = " + " | ".join(f"'{n}'" for n in icons) + ";\n"
ts += "export const ICONS: Record<IconName, { d?: string; fill?: boolean; raw?: string }[]> = " + json.dumps(icons, ensure_ascii=False, indent=1) + ";\n"
out.write_text(ts, encoding="utf-8")
print("wrote", out, "icons:", len(icons), "non-path shapes:", sum(1 for v in icons.values() for p in v if "raw" in p))
